### PR TITLE
disable signing on MacOS and Linux

### PR DESCRIPTION
**Pull request by SabotageAndi**

### CODE REVIEW

**Comment by SabotageAndi** [comment]
resolves #12

**Comment by aslakhellesoy** [comment]
Thanks that was quick!

Release process wise - what do you suggest for signing releases? Just edit the file locally? Should I set up a certificate we can share to use for signing? (Could be shared in 1Password)

**Comment by SabotageAndi** [comment]
This is only strong name signing. It isn't something like real code signing.
It's more about identification as security.

Documentation: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

The key for it is this file: https://github.com/cucumber/gherkin-dotnet/blob/master/gherkin.snk
It has no password. Thats the "standard procedure" for .NET OSS projects for signing.

Some enterprises have conventions that the assemblies have to be signed and when you begin with it, all your dependencies need strong name signing. So everybody signes it with a key without password and checks the key in.

We have the same in SpecFlow.

**Comment by aslakhellesoy** [comment]
If I understand correctly, signing will only happen when the release is done from a Windows machine.

The [release process](https://github.com/cucumber/cucumber/blob/master/RELEASE_PROCESS.md) for everything in the monorepo is to release all implementations simultaneously. I do this on a Mac.

Do you think you could make it work on Linux/OS X?

**Comment by SabotageAndi** [comment]
Yes, signing is only done on a Windows machine.

Strong name signing is not implemented on MacOS/Linux in .NET Core. As long as this is not done, a release have to be done on Windows.
But for SpecFlow we need also to compile gherkin-dotnet for .NET 4.5. Which is also only supported on Windows.

**Pull request merged**
