### PR TITLE
[WIP] Fix travis build

### PR DESCRIPTION
**Pull request by SabotageAndi**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
We're getting there @SabotageAndi!

Unfortunately this broke Appveyor: https://ci.appveyor.com/project/aslakhellesoy/gherkin/build/1.0.210

Any idea how to fix that?

**Comment by aslakhellesoy** [comment]
Also broke the monorepo build: https://travis-ci.org/cucumber/cucumber/builds/369145110

**Comment by SabotageAndi** [comment]
You were to fast with the merging. ;-)
I wasn't finished yet with the fix, that's why I put the [WIP] (work in progress) tag in the name of the PR.
Don't you use such tags in cucumber? I saw them a lot in other oss projects and interpreted it as common understanding.

**Comment by aslakhellesoy** [comment]
Haha ok my bad :-) I was too quick on the trigger. 
Take your time.

**Pull request merged**
