### PR TITLE
Fix double protocol in Berg GitHub url

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Thanks!

**Comment by nschonni** [comment]
FYI, not sure if you rebased this out on purpose, but it isn't in master anymore.

**Comment by brasmusson** [comment]
The root problem is that all changes to any of the gherkin-\* projects should be make in the [gherkin](https://github.com/cucumber/gherkin) project, and then push to the gherkin-\* projects, see [gherkin/CONTIBUTING.md](https://github.com/cucumber/gherkin/blob/master/CONTRIBUTING.md#contributing-to-gherkin). Because this change was made in this project (and not immediately after the merge pulled to the [gherkin](https://github.com/cucumber/gherkin) project), it was overwritten by the v4.0.0 release when it was pushed from the [gherkin](https://github.com/cucumber/gherkin) project.

**Comment by aslakhellesoy** [comment]
I originalmy merged the PR from my phone and didn't notice at the time it was done in the wrong repo. Please send us a new PR in the gherkin repo.

**Pull request merged**
